name: polished-blackstone-button
version: '${version}'

main: kik.polishedBlackstoneButton.PolishedBlackstoneButton
paperPluginLoader: kik.polishedBlackstoneButton.PolishedBlackstoneButtonLoader
api-version: '26.1.2'
load: POSTWORLD
commands:
  polishedblackstonebutton:
    description: "polishedblackstonebutton"
    usage: "polishedblackstonebutton polishedblackstonebutton polishedblackstonebutton>"
